language: C
dist: trusty
sudo: false

addons:
  apt:
    packages:
    - bmake
    - mawk
    - busybox-static
    - gawk

install:
  - mawk -W version 2>&1 | head -n 1
  - busybox | head -n 1
  - gawk --version | head -n 1

script: bmake test

env:
  matrix:
    - AWK=mawk
    - AWK="busybox awk"
    - AWK=gawk
