language: C
dist: trusty
sudo: false

addons:
  apt:
    packages:
    - bmake
    - original-awk
    - gawk
    - busybox-static
    - mawk

install:
  - original-awk --version
  - gawk --version | head -n 1
  - busybox | head -n 1
  - mawk -W version 2>&1 | head -n 1

script: bmake test

env:
  matrix:
    - AWK=original-awk
    - AWK=gawk
    - AWK="busybox awk"
    - AWK=mawk
