language: C
dist: trusty
sudo: false

addons:
  apt:
    packages:
    - bmake
    - mawk
    - busybox-static
    - gawk

script: bmake test

env:
  matrix:
    - AWK=mawk
    - AWK="busybox awk"
    - AWK=gawk
