language: C # because ya know, we're like compiling bmake.
dist: trusty
sudo: required

addons:
  apt:
    packages:
    #- bmake
    - gawk
    - mawk

install:
  - wget www.crufty.net/ftp/pub/sjg/bmake.tar.gz
  - tar xvf bmake.tar.gz
  - cd bmake && ./configure && sh ./make-bootstrap.sh && sudo make install

script: bmake test
